#!/bin/sh /etc/rc.common

START=30
USE_PROCD=1

DNS_SNOOPING_BIN=/usr/sbin/DNS_Snooping

start_service()
{
	procd_open_instance
	procd_set_param command "$DNS_SNOOPING_BIN"
	procd_set_param respawn
	procd_close_instance

}

restart()
{
	stop "$@"
	sleep 1
	start "$@"
}
